export { default as ArrowRight } from './icon-arrow-right.svg?react';
export { default as Cart } from './icon-cart.svg?react';
export { default as CashOnDelivery } from './icon-cash-on-delivery.svg?react';
export { default as Facebook } from './icon-facebook.svg?react';
export { default as Hamburger } from './icon-hamburger.svg';
export { default as Logo } from './icon-logo.svg?react';
export { default as OrderConfirmation } from './icon-order-confirmation.svg';
export { default as Instagram } from './icon-instagram.svg?react';
export { default as Twitter } from './icon-twitter.svg?react';
